/*
 * RelationalAI SDK
 *
 * This is a Client SDK for RelationalAI
 *
 * API version: 1.2.0
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// IntegrityConstraintProblem struct for IntegrityConstraintProblem
type IntegrityConstraintProblem struct {
	AbstractProblem
	Exception string `json:"exception"`
}

// NewIntegrityConstraintProblem instantiates a new IntegrityConstraintProblem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrityConstraintProblem(exception string, ) *IntegrityConstraintProblem {
	this := IntegrityConstraintProblem{}
	this.Exception = exception
	return &this
}

// NewIntegrityConstraintProblemWithDefaults instantiates a new IntegrityConstraintProblem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrityConstraintProblemWithDefaults() *IntegrityConstraintProblem {
	this := IntegrityConstraintProblem{}
	var exception string = ""
	this.Exception = exception
	return &this
}

// GetException returns the Exception field value
func (o *IntegrityConstraintProblem) GetException() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Exception
}

// GetExceptionOk returns a tuple with the Exception field value
// and a boolean to check if the value has been set.
func (o *IntegrityConstraintProblem) GetExceptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Exception, true
}

// SetException sets field value
func (o *IntegrityConstraintProblem) SetException(v string) {
	o.Exception = v
}

func (o IntegrityConstraintProblem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedAbstractProblem, errAbstractProblem := json.Marshal(o.AbstractProblem)
	if errAbstractProblem != nil {
		return []byte{}, errAbstractProblem
	}
	errAbstractProblem = json.Unmarshal([]byte(serializedAbstractProblem), &toSerialize)
	if errAbstractProblem != nil {
		return []byte{}, errAbstractProblem
	}
	if true {
		toSerialize["exception"] = o.Exception
	}
	return json.Marshal(toSerialize)
}

type NullableIntegrityConstraintProblem struct {
	value *IntegrityConstraintProblem
	isSet bool
}

func (v NullableIntegrityConstraintProblem) Get() *IntegrityConstraintProblem {
	return v.value
}

func (v *NullableIntegrityConstraintProblem) Set(val *IntegrityConstraintProblem) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrityConstraintProblem) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrityConstraintProblem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrityConstraintProblem(val *IntegrityConstraintProblem) *NullableIntegrityConstraintProblem {
	return &NullableIntegrityConstraintProblem{value: val, isSet: true}
}

func (v NullableIntegrityConstraintProblem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrityConstraintProblem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


