/*
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * API version: 1.1.3
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// FileSchema struct for FileSchema
type FileSchema struct {
	Type string `json:"type"`
}

// NewFileSchema instantiates a new FileSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileSchema(type_ string, ) *FileSchema {
	this := FileSchema{}
	this.Type = type_
	return &this
}

// NewFileSchemaWithDefaults instantiates a new FileSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileSchemaWithDefaults() *FileSchema {
	this := FileSchema{}
	var type_ string = ""
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *FileSchema) GetType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FileSchema) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FileSchema) SetType(v string) {
	o.Type = v
}

func (o FileSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableFileSchema struct {
	value *FileSchema
	isSet bool
}

func (v NullableFileSchema) Get() *FileSchema {
	return v.value
}

func (v *NullableFileSchema) Set(val *FileSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableFileSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableFileSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileSchema(val *FileSchema) *NullableFileSchema {
	return &NullableFileSchema{value: val, isSet: true}
}

func (v NullableFileSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


