/*
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * API version: 1.1.3
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// IntegrityConstraintViolation struct for IntegrityConstraintViolation
type IntegrityConstraintViolation struct {
	AbstractProblem
	Sources []ICViolation `json:"sources,omitempty"`
}

// NewIntegrityConstraintViolation instantiates a new IntegrityConstraintViolation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrityConstraintViolation() *IntegrityConstraintViolation {
	this := IntegrityConstraintViolation{}
	return &this
}

// NewIntegrityConstraintViolationWithDefaults instantiates a new IntegrityConstraintViolation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrityConstraintViolationWithDefaults() *IntegrityConstraintViolation {
	this := IntegrityConstraintViolation{}
	return &this
}

// GetSources returns the Sources field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntegrityConstraintViolation) GetSources() []ICViolation {
	if o == nil  {
		var ret []ICViolation
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntegrityConstraintViolation) GetSourcesOk() (*[]ICViolation, bool) {
	if o == nil || o.Sources == nil {
		return nil, false
	}
	return &o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *IntegrityConstraintViolation) HasSources() bool {
	if o != nil && o.Sources != nil {
		return true
	}

	return false
}

// SetSources gets a reference to the given []ICViolation and assigns it to the Sources field.
func (o *IntegrityConstraintViolation) SetSources(v []ICViolation) {
	o.Sources = v
}

func (o IntegrityConstraintViolation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedAbstractProblem, errAbstractProblem := json.Marshal(o.AbstractProblem)
	if errAbstractProblem != nil {
		return []byte{}, errAbstractProblem
	}
	errAbstractProblem = json.Unmarshal([]byte(serializedAbstractProblem), &toSerialize)
	if errAbstractProblem != nil {
		return []byte{}, errAbstractProblem
	}
	if o.Sources != nil {
		toSerialize["sources"] = o.Sources
	}
	return json.Marshal(toSerialize)
}

type NullableIntegrityConstraintViolation struct {
	value *IntegrityConstraintViolation
	isSet bool
}

func (v NullableIntegrityConstraintViolation) Get() *IntegrityConstraintViolation {
	return v.value
}

func (v *NullableIntegrityConstraintViolation) Set(val *IntegrityConstraintViolation) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrityConstraintViolation) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrityConstraintViolation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrityConstraintViolation(val *IntegrityConstraintViolation) *NullableIntegrityConstraintViolation {
	return &NullableIntegrityConstraintViolation{value: val, isSet: true}
}

func (v NullableIntegrityConstraintViolation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrityConstraintViolation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


