/*
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * API version: 1.1.3
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// S3Integration struct for S3Integration
type S3Integration struct {
	Integration
	Dummy NullableString `json:"dummy,omitempty"`
}

// NewS3Integration instantiates a new S3Integration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3Integration() *S3Integration {
	this := S3Integration{}
	return &this
}

// NewS3IntegrationWithDefaults instantiates a new S3Integration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3IntegrationWithDefaults() *S3Integration {
	this := S3Integration{}
	return &this
}

// GetDummy returns the Dummy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3Integration) GetDummy() string {
	if o == nil || o.Dummy.Get() == nil {
		var ret string
		return ret
	}
	return *o.Dummy.Get()
}

// GetDummyOk returns a tuple with the Dummy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3Integration) GetDummyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Dummy.Get(), o.Dummy.IsSet()
}

// HasDummy returns a boolean if a field has been set.
func (o *S3Integration) HasDummy() bool {
	if o != nil && o.Dummy.IsSet() {
		return true
	}

	return false
}

// SetDummy gets a reference to the given NullableString and assigns it to the Dummy field.
func (o *S3Integration) SetDummy(v string) {
	o.Dummy.Set(&v)
}
// SetDummyNil sets the value for Dummy to be an explicit nil
func (o *S3Integration) SetDummyNil() {
	o.Dummy.Set(nil)
}

// UnsetDummy ensures that no value is present for Dummy, not even an explicit nil
func (o *S3Integration) UnsetDummy() {
	o.Dummy.Unset()
}

func (o S3Integration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedIntegration, errIntegration := json.Marshal(o.Integration)
	if errIntegration != nil {
		return []byte{}, errIntegration
	}
	errIntegration = json.Unmarshal([]byte(serializedIntegration), &toSerialize)
	if errIntegration != nil {
		return []byte{}, errIntegration
	}
	if o.Dummy.IsSet() {
		toSerialize["dummy"] = o.Dummy.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableS3Integration struct {
	value *S3Integration
	isSet bool
}

func (v NullableS3Integration) Get() *S3Integration {
	return v.value
}

func (v *NullableS3Integration) Set(val *S3Integration) {
	v.value = val
	v.isSet = true
}

func (v NullableS3Integration) IsSet() bool {
	return v.isSet
}

func (v *NullableS3Integration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3Integration(val *S3Integration) *NullableS3Integration {
	return &NullableS3Integration{value: val, isSet: true}
}

func (v NullableS3Integration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3Integration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


