/*
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * API version: 1.1.3
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// SyntaxError struct for SyntaxError
type SyntaxError struct {
	AbstractProblem
	Next *SyntaxNode `json:"next,omitempty"`
	Node SyntaxNode `json:"node"`
	Trace LinkedList `json:"trace"`
}

// NewSyntaxError instantiates a new SyntaxError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyntaxError(node SyntaxNode, trace LinkedList, ) *SyntaxError {
	this := SyntaxError{}
	this.Node = node
	this.Trace = trace
	return &this
}

// NewSyntaxErrorWithDefaults instantiates a new SyntaxError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyntaxErrorWithDefaults() *SyntaxError {
	this := SyntaxError{}
	return &this
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *SyntaxError) GetNext() SyntaxNode {
	if o == nil || o.Next == nil {
		var ret SyntaxNode
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyntaxError) GetNextOk() (*SyntaxNode, bool) {
	if o == nil || o.Next == nil {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *SyntaxError) HasNext() bool {
	if o != nil && o.Next != nil {
		return true
	}

	return false
}

// SetNext gets a reference to the given SyntaxNode and assigns it to the Next field.
func (o *SyntaxError) SetNext(v SyntaxNode) {
	o.Next = &v
}

// GetNode returns the Node field value
func (o *SyntaxError) GetNode() SyntaxNode {
	if o == nil  {
		var ret SyntaxNode
		return ret
	}

	return o.Node
}

// GetNodeOk returns a tuple with the Node field value
// and a boolean to check if the value has been set.
func (o *SyntaxError) GetNodeOk() (*SyntaxNode, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Node, true
}

// SetNode sets field value
func (o *SyntaxError) SetNode(v SyntaxNode) {
	o.Node = v
}

// GetTrace returns the Trace field value
func (o *SyntaxError) GetTrace() LinkedList {
	if o == nil  {
		var ret LinkedList
		return ret
	}

	return o.Trace
}

// GetTraceOk returns a tuple with the Trace field value
// and a boolean to check if the value has been set.
func (o *SyntaxError) GetTraceOk() (*LinkedList, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Trace, true
}

// SetTrace sets field value
func (o *SyntaxError) SetTrace(v LinkedList) {
	o.Trace = v
}

func (o SyntaxError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedAbstractProblem, errAbstractProblem := json.Marshal(o.AbstractProblem)
	if errAbstractProblem != nil {
		return []byte{}, errAbstractProblem
	}
	errAbstractProblem = json.Unmarshal([]byte(serializedAbstractProblem), &toSerialize)
	if errAbstractProblem != nil {
		return []byte{}, errAbstractProblem
	}
	if o.Next != nil {
		toSerialize["next"] = o.Next
	}
	if true {
		toSerialize["node"] = o.Node
	}
	if true {
		toSerialize["trace"] = o.Trace
	}
	return json.Marshal(toSerialize)
}

type NullableSyntaxError struct {
	value *SyntaxError
	isSet bool
}

func (v NullableSyntaxError) Get() *SyntaxError {
	return v.value
}

func (v *NullableSyntaxError) Set(val *SyntaxError) {
	v.value = val
	v.isSet = true
}

func (v NullableSyntaxError) IsSet() bool {
	return v.isSet
}

func (v *NullableSyntaxError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyntaxError(val *SyntaxError) *NullableSyntaxError {
	return &NullableSyntaxError{value: val, isSet: true}
}

func (v NullableSyntaxError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyntaxError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


