/*
 * RelationalAI SDK
 *
 * This is a Client SDK for RelationalAI
 *
 * API version: 1.1.3
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// JSONFileSchema struct for JSONFileSchema
type JSONFileSchema struct {
	FileSchema
	Dummy NullableString `json:"dummy,omitempty"`
}

// NewJSONFileSchema instantiates a new JSONFileSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJSONFileSchema() *JSONFileSchema {
	this := JSONFileSchema{}
	return &this
}

// NewJSONFileSchemaWithDefaults instantiates a new JSONFileSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJSONFileSchemaWithDefaults() *JSONFileSchema {
	this := JSONFileSchema{}
	return &this
}

// GetDummy returns the Dummy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JSONFileSchema) GetDummy() string {
	if o == nil || o.Dummy.Get() == nil {
		var ret string
		return ret
	}
	return *o.Dummy.Get()
}

// GetDummyOk returns a tuple with the Dummy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JSONFileSchema) GetDummyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Dummy.Get(), o.Dummy.IsSet()
}

// HasDummy returns a boolean if a field has been set.
func (o *JSONFileSchema) HasDummy() bool {
	if o != nil && o.Dummy.IsSet() {
		return true
	}

	return false
}

// SetDummy gets a reference to the given NullableString and assigns it to the Dummy field.
func (o *JSONFileSchema) SetDummy(v string) {
	o.Dummy.Set(&v)
}
// SetDummyNil sets the value for Dummy to be an explicit nil
func (o *JSONFileSchema) SetDummyNil() {
	o.Dummy.Set(nil)
}

// UnsetDummy ensures that no value is present for Dummy, not even an explicit nil
func (o *JSONFileSchema) UnsetDummy() {
	o.Dummy.Unset()
}

func (o JSONFileSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedFileSchema, errFileSchema := json.Marshal(o.FileSchema)
	if errFileSchema != nil {
		return []byte{}, errFileSchema
	}
	errFileSchema = json.Unmarshal([]byte(serializedFileSchema), &toSerialize)
	if errFileSchema != nil {
		return []byte{}, errFileSchema
	}
	if o.Dummy.IsSet() {
		toSerialize["dummy"] = o.Dummy.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableJSONFileSchema struct {
	value *JSONFileSchema
	isSet bool
}

func (v NullableJSONFileSchema) Get() *JSONFileSchema {
	return v.value
}

func (v *NullableJSONFileSchema) Set(val *JSONFileSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableJSONFileSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableJSONFileSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJSONFileSchema(val *JSONFileSchema) *NullableJSONFileSchema {
	return &NullableJSONFileSchema{value: val, isSet: true}
}

func (v NullableJSONFileSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJSONFileSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


