/*
 * RelationalAI SDK
 *
 * This is a Client SDK for RelationalAI
 *
 * API version: 1.2.0
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// IntegrityConstraintProblemAllOf struct for IntegrityConstraintProblemAllOf
type IntegrityConstraintProblemAllOf struct {
	Exception string `json:"exception"`
}

// NewIntegrityConstraintProblemAllOf instantiates a new IntegrityConstraintProblemAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrityConstraintProblemAllOf(exception string, ) *IntegrityConstraintProblemAllOf {
	this := IntegrityConstraintProblemAllOf{}
	this.Exception = exception
	return &this
}

// NewIntegrityConstraintProblemAllOfWithDefaults instantiates a new IntegrityConstraintProblemAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrityConstraintProblemAllOfWithDefaults() *IntegrityConstraintProblemAllOf {
	this := IntegrityConstraintProblemAllOf{}
	var exception string = ""
	this.Exception = exception
	return &this
}

// GetException returns the Exception field value
func (o *IntegrityConstraintProblemAllOf) GetException() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Exception
}

// GetExceptionOk returns a tuple with the Exception field value
// and a boolean to check if the value has been set.
func (o *IntegrityConstraintProblemAllOf) GetExceptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Exception, true
}

// SetException sets field value
func (o *IntegrityConstraintProblemAllOf) SetException(v string) {
	o.Exception = v
}

func (o IntegrityConstraintProblemAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["exception"] = o.Exception
	}
	return json.Marshal(toSerialize)
}

type NullableIntegrityConstraintProblemAllOf struct {
	value *IntegrityConstraintProblemAllOf
	isSet bool
}

func (v NullableIntegrityConstraintProblemAllOf) Get() *IntegrityConstraintProblemAllOf {
	return v.value
}

func (v *NullableIntegrityConstraintProblemAllOf) Set(val *IntegrityConstraintProblemAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrityConstraintProblemAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrityConstraintProblemAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrityConstraintProblemAllOf(val *IntegrityConstraintProblemAllOf) *NullableIntegrityConstraintProblemAllOf {
	return &NullableIntegrityConstraintProblemAllOf{value: val, isSet: true}
}

func (v NullableIntegrityConstraintProblemAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrityConstraintProblemAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


