/*
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * API version: 1.1.3
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// LinkedList struct for LinkedList
type LinkedList struct {
	Type string `json:"type"`
}

// NewLinkedList instantiates a new LinkedList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkedList(type_ string, ) *LinkedList {
	this := LinkedList{}
	this.Type = type_
	return &this
}

// NewLinkedListWithDefaults instantiates a new LinkedList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkedListWithDefaults() *LinkedList {
	this := LinkedList{}
	var type_ string = ""
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *LinkedList) GetType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *LinkedList) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *LinkedList) SetType(v string) {
	o.Type = v
}

func (o LinkedList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableLinkedList struct {
	value *LinkedList
	isSet bool
}

func (v NullableLinkedList) Get() *LinkedList {
	return v.value
}

func (v *NullableLinkedList) Set(val *LinkedList) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkedList) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkedList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkedList(val *LinkedList) *NullableLinkedList {
	return &NullableLinkedList{value: val, isSet: true}
}

func (v NullableLinkedList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkedList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


