/*
 * RelationalAI SDK
 *
 * This is a Client SDK for RelationalAI
 *
 * API version: 1.1.3
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InstallActionAllOf struct for InstallActionAllOf
type InstallActionAllOf struct {
	Sources []Source `json:"sources,omitempty"`
}

// NewInstallActionAllOf instantiates a new InstallActionAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstallActionAllOf() *InstallActionAllOf {
	this := InstallActionAllOf{}
	return &this
}

// NewInstallActionAllOfWithDefaults instantiates a new InstallActionAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstallActionAllOfWithDefaults() *InstallActionAllOf {
	this := InstallActionAllOf{}
	return &this
}

// GetSources returns the Sources field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstallActionAllOf) GetSources() []Source {
	if o == nil  {
		var ret []Source
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstallActionAllOf) GetSourcesOk() (*[]Source, bool) {
	if o == nil || o.Sources == nil {
		return nil, false
	}
	return &o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *InstallActionAllOf) HasSources() bool {
	if o != nil && o.Sources != nil {
		return true
	}

	return false
}

// SetSources gets a reference to the given []Source and assigns it to the Sources field.
func (o *InstallActionAllOf) SetSources(v []Source) {
	o.Sources = v
}

func (o InstallActionAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Sources != nil {
		toSerialize["sources"] = o.Sources
	}
	return json.Marshal(toSerialize)
}

type NullableInstallActionAllOf struct {
	value *InstallActionAllOf
	isSet bool
}

func (v NullableInstallActionAllOf) Get() *InstallActionAllOf {
	return v.value
}

func (v *NullableInstallActionAllOf) Set(val *InstallActionAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableInstallActionAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableInstallActionAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstallActionAllOf(val *InstallActionAllOf) *NullableInstallActionAllOf {
	return &NullableInstallActionAllOf{value: val, isSet: true}
}

func (v NullableInstallActionAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstallActionAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


