/*
 * RelationalAI SDK
 *
 * This is a Client SDK for RelationalAI
 *
 * API version: 1.2.0
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// UpdateActionAllOf struct for UpdateActionAllOf
type UpdateActionAllOf struct {
	Delta []PairAnyValueAnyValue `json:"delta,omitempty"`
	Rel RelKey `json:"rel"`
	Updates []PairAnyValueAnyValue `json:"updates,omitempty"`
}

// NewUpdateActionAllOf instantiates a new UpdateActionAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateActionAllOf(rel RelKey, ) *UpdateActionAllOf {
	this := UpdateActionAllOf{}
	this.Rel = rel
	return &this
}

// NewUpdateActionAllOfWithDefaults instantiates a new UpdateActionAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateActionAllOfWithDefaults() *UpdateActionAllOf {
	this := UpdateActionAllOf{}
	return &this
}

// GetDelta returns the Delta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateActionAllOf) GetDelta() []PairAnyValueAnyValue {
	if o == nil  {
		var ret []PairAnyValueAnyValue
		return ret
	}
	return o.Delta
}

// GetDeltaOk returns a tuple with the Delta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateActionAllOf) GetDeltaOk() (*[]PairAnyValueAnyValue, bool) {
	if o == nil || o.Delta == nil {
		return nil, false
	}
	return &o.Delta, true
}

// HasDelta returns a boolean if a field has been set.
func (o *UpdateActionAllOf) HasDelta() bool {
	if o != nil && o.Delta != nil {
		return true
	}

	return false
}

// SetDelta gets a reference to the given []PairAnyValueAnyValue and assigns it to the Delta field.
func (o *UpdateActionAllOf) SetDelta(v []PairAnyValueAnyValue) {
	o.Delta = v
}

// GetRel returns the Rel field value
func (o *UpdateActionAllOf) GetRel() RelKey {
	if o == nil  {
		var ret RelKey
		return ret
	}

	return o.Rel
}

// GetRelOk returns a tuple with the Rel field value
// and a boolean to check if the value has been set.
func (o *UpdateActionAllOf) GetRelOk() (*RelKey, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Rel, true
}

// SetRel sets field value
func (o *UpdateActionAllOf) SetRel(v RelKey) {
	o.Rel = v
}

// GetUpdates returns the Updates field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateActionAllOf) GetUpdates() []PairAnyValueAnyValue {
	if o == nil  {
		var ret []PairAnyValueAnyValue
		return ret
	}
	return o.Updates
}

// GetUpdatesOk returns a tuple with the Updates field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateActionAllOf) GetUpdatesOk() (*[]PairAnyValueAnyValue, bool) {
	if o == nil || o.Updates == nil {
		return nil, false
	}
	return &o.Updates, true
}

// HasUpdates returns a boolean if a field has been set.
func (o *UpdateActionAllOf) HasUpdates() bool {
	if o != nil && o.Updates != nil {
		return true
	}

	return false
}

// SetUpdates gets a reference to the given []PairAnyValueAnyValue and assigns it to the Updates field.
func (o *UpdateActionAllOf) SetUpdates(v []PairAnyValueAnyValue) {
	o.Updates = v
}

func (o UpdateActionAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Delta != nil {
		toSerialize["delta"] = o.Delta
	}
	if true {
		toSerialize["rel"] = o.Rel
	}
	if o.Updates != nil {
		toSerialize["updates"] = o.Updates
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateActionAllOf struct {
	value *UpdateActionAllOf
	isSet bool
}

func (v NullableUpdateActionAllOf) Get() *UpdateActionAllOf {
	return v.value
}

func (v *NullableUpdateActionAllOf) Set(val *UpdateActionAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateActionAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateActionAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateActionAllOf(val *UpdateActionAllOf) *NullableUpdateActionAllOf {
	return &NullableUpdateActionAllOf{value: val, isSet: true}
}

func (v NullableUpdateActionAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateActionAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


