/*
 * RelationalAI SDK
 *
 * This is a Client SDK for RelationalAI
 *
 * API version: 1.2.0
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ApplAllOf struct for ApplAllOf
type ApplAllOf struct {
	Arguments []SyntaxNode `json:"arguments,omitempty"`
	Error bool `json:"error"`
	Missing bool `json:"missing"`
	Range Range `json:"range"`
	Symbol string `json:"symbol"`
}

// NewApplAllOf instantiates a new ApplAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplAllOf(error_ bool, missing bool, range_ Range, symbol string, ) *ApplAllOf {
	this := ApplAllOf{}
	this.Error = error_
	this.Missing = missing
	this.Range = range_
	this.Symbol = symbol
	return &this
}

// NewApplAllOfWithDefaults instantiates a new ApplAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplAllOfWithDefaults() *ApplAllOf {
	this := ApplAllOf{}
	var error_ bool = false
	this.Error = error_
	var missing bool = false
	this.Missing = missing
	var symbol string = ""
	this.Symbol = symbol
	return &this
}

// GetArguments returns the Arguments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApplAllOf) GetArguments() []SyntaxNode {
	if o == nil  {
		var ret []SyntaxNode
		return ret
	}
	return o.Arguments
}

// GetArgumentsOk returns a tuple with the Arguments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApplAllOf) GetArgumentsOk() (*[]SyntaxNode, bool) {
	if o == nil || o.Arguments == nil {
		return nil, false
	}
	return &o.Arguments, true
}

// HasArguments returns a boolean if a field has been set.
func (o *ApplAllOf) HasArguments() bool {
	if o != nil && o.Arguments != nil {
		return true
	}

	return false
}

// SetArguments gets a reference to the given []SyntaxNode and assigns it to the Arguments field.
func (o *ApplAllOf) SetArguments(v []SyntaxNode) {
	o.Arguments = v
}

// GetError returns the Error field value
func (o *ApplAllOf) GetError() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ApplAllOf) GetErrorOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ApplAllOf) SetError(v bool) {
	o.Error = v
}

// GetMissing returns the Missing field value
func (o *ApplAllOf) GetMissing() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.Missing
}

// GetMissingOk returns a tuple with the Missing field value
// and a boolean to check if the value has been set.
func (o *ApplAllOf) GetMissingOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Missing, true
}

// SetMissing sets field value
func (o *ApplAllOf) SetMissing(v bool) {
	o.Missing = v
}

// GetRange returns the Range field value
func (o *ApplAllOf) GetRange() Range {
	if o == nil  {
		var ret Range
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *ApplAllOf) GetRangeOk() (*Range, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Range, true
}

// SetRange sets field value
func (o *ApplAllOf) SetRange(v Range) {
	o.Range = v
}

// GetSymbol returns the Symbol field value
func (o *ApplAllOf) GetSymbol() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *ApplAllOf) GetSymbolOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *ApplAllOf) SetSymbol(v string) {
	o.Symbol = v
}

func (o ApplAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Arguments != nil {
		toSerialize["arguments"] = o.Arguments
	}
	if true {
		toSerialize["error"] = o.Error
	}
	if true {
		toSerialize["missing"] = o.Missing
	}
	if true {
		toSerialize["range"] = o.Range
	}
	if true {
		toSerialize["symbol"] = o.Symbol
	}
	return json.Marshal(toSerialize)
}

type NullableApplAllOf struct {
	value *ApplAllOf
	isSet bool
}

func (v NullableApplAllOf) Get() *ApplAllOf {
	return v.value
}

func (v *NullableApplAllOf) Set(val *ApplAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableApplAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableApplAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplAllOf(val *ApplAllOf) *NullableApplAllOf {
	return &NullableApplAllOf{value: val, isSet: true}
}

func (v NullableApplAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


