/*
 * RelationalAI SDK
 *
 * This is a Client SDK for RelationalAI
 *
 * API version: 1.1.3
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CardinalityActionAllOf struct for CardinalityActionAllOf
type CardinalityActionAllOf struct {
	Relname NullableString `json:"relname,omitempty"`
}

// NewCardinalityActionAllOf instantiates a new CardinalityActionAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardinalityActionAllOf() *CardinalityActionAllOf {
	this := CardinalityActionAllOf{}
	return &this
}

// NewCardinalityActionAllOfWithDefaults instantiates a new CardinalityActionAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardinalityActionAllOfWithDefaults() *CardinalityActionAllOf {
	this := CardinalityActionAllOf{}
	return &this
}

// GetRelname returns the Relname field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CardinalityActionAllOf) GetRelname() string {
	if o == nil || o.Relname.Get() == nil {
		var ret string
		return ret
	}
	return *o.Relname.Get()
}

// GetRelnameOk returns a tuple with the Relname field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CardinalityActionAllOf) GetRelnameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Relname.Get(), o.Relname.IsSet()
}

// HasRelname returns a boolean if a field has been set.
func (o *CardinalityActionAllOf) HasRelname() bool {
	if o != nil && o.Relname.IsSet() {
		return true
	}

	return false
}

// SetRelname gets a reference to the given NullableString and assigns it to the Relname field.
func (o *CardinalityActionAllOf) SetRelname(v string) {
	o.Relname.Set(&v)
}
// SetRelnameNil sets the value for Relname to be an explicit nil
func (o *CardinalityActionAllOf) SetRelnameNil() {
	o.Relname.Set(nil)
}

// UnsetRelname ensures that no value is present for Relname, not even an explicit nil
func (o *CardinalityActionAllOf) UnsetRelname() {
	o.Relname.Unset()
}

func (o CardinalityActionAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Relname.IsSet() {
		toSerialize["relname"] = o.Relname.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableCardinalityActionAllOf struct {
	value *CardinalityActionAllOf
	isSet bool
}

func (v NullableCardinalityActionAllOf) Get() *CardinalityActionAllOf {
	return v.value
}

func (v *NullableCardinalityActionAllOf) Set(val *CardinalityActionAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCardinalityActionAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCardinalityActionAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardinalityActionAllOf(val *CardinalityActionAllOf) *NullableCardinalityActionAllOf {
	return &NullableCardinalityActionAllOf{value: val, isSet: true}
}

func (v NullableCardinalityActionAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardinalityActionAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


