/*
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * API version: 1.1.3
 * Contact: support@relational.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// IntegrityConstraintViolationAllOf struct for IntegrityConstraintViolationAllOf
type IntegrityConstraintViolationAllOf struct {
	Sources []ICViolation `json:"sources,omitempty"`
}

// NewIntegrityConstraintViolationAllOf instantiates a new IntegrityConstraintViolationAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrityConstraintViolationAllOf() *IntegrityConstraintViolationAllOf {
	this := IntegrityConstraintViolationAllOf{}
	return &this
}

// NewIntegrityConstraintViolationAllOfWithDefaults instantiates a new IntegrityConstraintViolationAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrityConstraintViolationAllOfWithDefaults() *IntegrityConstraintViolationAllOf {
	this := IntegrityConstraintViolationAllOf{}
	return &this
}

// GetSources returns the Sources field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntegrityConstraintViolationAllOf) GetSources() []ICViolation {
	if o == nil  {
		var ret []ICViolation
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntegrityConstraintViolationAllOf) GetSourcesOk() (*[]ICViolation, bool) {
	if o == nil || o.Sources == nil {
		return nil, false
	}
	return &o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *IntegrityConstraintViolationAllOf) HasSources() bool {
	if o != nil && o.Sources != nil {
		return true
	}

	return false
}

// SetSources gets a reference to the given []ICViolation and assigns it to the Sources field.
func (o *IntegrityConstraintViolationAllOf) SetSources(v []ICViolation) {
	o.Sources = v
}

func (o IntegrityConstraintViolationAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Sources != nil {
		toSerialize["sources"] = o.Sources
	}
	return json.Marshal(toSerialize)
}

type NullableIntegrityConstraintViolationAllOf struct {
	value *IntegrityConstraintViolationAllOf
	isSet bool
}

func (v NullableIntegrityConstraintViolationAllOf) Get() *IntegrityConstraintViolationAllOf {
	return v.value
}

func (v *NullableIntegrityConstraintViolationAllOf) Set(val *IntegrityConstraintViolationAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrityConstraintViolationAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrityConstraintViolationAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrityConstraintViolationAllOf(val *IntegrityConstraintViolationAllOf) *NullableIntegrityConstraintViolationAllOf {
	return &NullableIntegrityConstraintViolationAllOf{value: val, isSet: true}
}

func (v NullableIntegrityConstraintViolationAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrityConstraintViolationAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


